<?php


namespace EMedia\Api\Tests\Feature;


use App\Controllers\Http\TestController;
use EMedia\Api\Tests\TestCase;

class TestsAutoGeneratedTest extends TestCase
{

	/**
	 *
	 * This is the test to test if tests are generated. Yeah, read that again.
	 *
	 */
	public function testAutomatedTestsAreGenerated()
	{
		$specFile = public_path('docs/postman_collection.yml');

		foreach ($this->generatedTestFilePaths() as $path) {
			$this->assertFileDoesNotExist($path);
		}

		$testUserId = 4;
		$this->setApiKey();
		$this->mockDataSources($testUserId);

		$this->artisan("generate:docs --test-user-id={$testUserId}");
		$this->assertFileExists($specFile);

		$this->artisan("generate:api-tests --force");

		foreach ($this->generatedTestFilePaths() as $path) {
			$this->assertFileExists($path);
		}
	}
}
